### ISSUE TITLE
DB#InitCollab Endpoint

### ISSUE THREAD

**Issue by krashanoff** [uclaacm/teach-la-go-backend#30]
To start a collaborative coding session, we're going to need to create an endpoint that will set up a session's websocket, and arbitrate the editor events between the two.

All this endpoint needs to do that's special is forward editor events from one client to the others, and handle save events for the program they are all working on.

For more reading, take a look at [echo's documentation on websockets](https://echo.labstack.com/cookbook/websocket).

For some starter code, please review the [`collab`](https://github.com/uclaacm/teach-la-go-backend/tree/collab) branch.

**Comment by joshSi** [comment]
Hey just to clarify, the endpoint should be called InitCollab not CreateCollab right? Just noticed this

**Comment by krashanoff** [comment]
Hey Josh. This is the wrong issue. I thought the linked pull request would close it out, but it didn't. The handler for creating a collaborative session `CreateCollab` has already been made. The issue that I have assigned you to is #33. Apologies!
