### ISSUE TITLE
Refactor db#DB.GetClassMembers into a handler function

### ISSUE THREAD

**Issue by lumisphere902** [uclaacm/teach-la-go-backend#94]
See https://github.com/uclaacm/teach-la-go-backend/wiki/How-to-refactor-a-Backend-API, or https://github.com/uclaacm/teach-la-go-backend/pull/57 for an example. This will also involve moving the `loadClass` function to `db/db.go`. You can find the function in https://github.com/uclaacm/teach-la-go-backend/blob/master/db/class.go#L230

**Comment by winterberry123** [comment]
#147
